### ISSUE TITLE
How to use it in unity

### ISSUE THREAD

**Issue by Hocemedinbg** [HosniMansour/Unity3DFaceTtracking#2]
Hi,
Sorry, I'm a beginner, but how to open the project in Unity and use it like you do in the video ? I've tried "Assets > Import Package > Custom Package" but I did not find it.

**Comment by HosniMansour** [comment]
Did you the camera window started ? Maybe try to run OpenFaceFaceLandmarkVid on it own first and see if it works fine with you https://github.com/cmusatyalab/openface

**Comment by Hocemedinbg** [comment]
It works very fine on its own and yes, the camera window started, but, as I said, I don't know how to install and open the project in Unity.

**Comment by HosniMansour** [comment]
You should be able to open sc_hosni.unity inside Assets folder ( you can also create your own scene) but as I remember there are no changes required, If the DLL files are inside the main unity folder then when you play the scene the camera window will open and it will be like the video.
